//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PaisesEntities : DbContext
    {
        public PaisesEntities()
            : base("name=PaisesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<Paises> Paises { get; set; }
        public virtual DbSet<Imagenes> Imagenes { get; set; }
    
        public virtual ObjectResult<GetAllPaises_Result> GetAllPaises()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllPaises_Result>("GetAllPaises");
        }
    }
}
